//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace universal_tagger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("universal_tagger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to commit all changes?.
        /// </summary>
        internal static string commit_warning {
            get {
                return ResourceManager.GetString("commit_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aar||aa|Afar|afar
        ///abk||ab|Abkhazian|abkhaze
        ///ace|||Achinese|aceh
        ///ach|||Acoli|acoli
        ///ada|||Adangme|adangme
        ///ady|||Adyghe; Adygei|adyghé
        ///afa|||Afro-Asiatic (Other)|afro-asiatiques, autres langues
        ///afh|||Afrihili|afrihili
        ///afr||af|Afrikaans|afrikaans
        ///ain|||Ainu|aïnou
        ///aka||ak|Akan|akan
        ///akk|||Akkadian|akkadien
        ///alb|sqi|sq|Albanian|albanais
        ///ale|||Aleut|aléoute
        ///alg|||Algonquian languages|algonquines, langues
        ///alt|||Southern Altai|altai du Sud
        ///amh||am|Amharic|amharique
        ///ang|||English, Old (ca.450-1100)|anglo-saxon (ca.450- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ISO_639_2 {
            get {
                return ResourceManager.GetString("ISO_639_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cause you to lose all pending changes. Do you with to save first?.
        /// </summary>
        internal static string refresh_warning {
            get {
                return ResourceManager.GetString("refresh_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Pending Changes?.
        /// </summary>
        internal static string save_pending {
            get {
                return ResourceManager.GetString("save_pending", resourceCulture);
            }
        }
    }
}
