//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music_tagger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("music_tagger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _case {
            get {
                object obj = ResourceManager.GetObject("_case", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _enum {
            get {
                object obj = ResourceManager.GetObject("_enum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to commit all changes?.
        /// </summary>
        internal static string commit_warning {
            get {
                return ResourceManager.GetString("commit_warning", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap decrease_enum {
            get {
                object obj = ResourceManager.GetObject("decrease_enum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delfilter {
            get {
                object obj = ResourceManager.GetObject("delfilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delv1 {
            get {
                object obj = ResourceManager.GetObject("delv1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delv2 {
            get {
                object obj = ResourceManager.GetObject("delv2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file2v1 {
            get {
                object obj = ResourceManager.GetObject("file2v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap file2v2 {
            get {
                object obj = ResourceManager.GetObject("file2v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap increase_enum {
            get {
                object obj = ResourceManager.GetObject("increase_enum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aar||aa|Afar|afar
        ///abk||ab|Abkhazian|abkhaze
        ///ace|||Achinese|aceh
        ///ach|||Acoli|acoli
        ///ada|||Adangme|adangme
        ///ady|||Adyghe; Adygei|adyghé
        ///afa|||Afro-Asiatic (Other)|afro-asiatiques, autres langues
        ///afh|||Afrihili|afrihili
        ///afr||af|Afrikaans|afrikaans
        ///ain|||Ainu|aïnou
        ///aka||ak|Akan|akan
        ///akk|||Akkadian|akkadien
        ///alb|sqi|sq|Albanian|albanais
        ///ale|||Aleut|aléoute
        ///alg|||Algonquian languages|algonquines, langues
        ///alt|||Southern Altai|altai du Sud
        ///amh||am|Amharic|amharique
        ///ang|||English, Old (ca.450-1100)|anglo-saxon (ca.450- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ISO_639_2 {
            get {
                return ResourceManager.GetString("ISO_639_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cause you to lose all pending changes. Do you with to save first?.
        /// </summary>
        internal static string refresh_warning {
            get {
                return ResourceManager.GetString("refresh_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Pending Changes.
        /// </summary>
        internal static string save_pending {
            get {
                return ResourceManager.GetString("save_pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing Ver. 1.
        /// </summary>
        internal static string showing_ver1 {
            get {
                return ResourceManager.GetString("showing_ver1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing Ver. 2.
        /// </summary>
        internal static string showing_ver2 {
            get {
                return ResourceManager.GetString("showing_ver2", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap shown {
            get {
                object obj = ResourceManager.GetObject("shown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transv1 {
            get {
                object obj = ResourceManager.GetObject("transv1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transv1v2 {
            get {
                object obj = ResourceManager.GetObject("transv1v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transv2 {
            get {
                object obj = ResourceManager.GetObject("transv2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap v1 {
            get {
                object obj = ResourceManager.GetObject("v1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap v1_many {
            get {
                object obj = ResourceManager.GetObject("v1_many", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap v12file {
            get {
                object obj = ResourceManager.GetObject("v12file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap v2 {
            get {
                object obj = ResourceManager.GetObject("v2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap v2_many {
            get {
                object obj = ResourceManager.GetObject("v2_many", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap v22file {
            get {
                object obj = ResourceManager.GetObject("v22file", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
