//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace music_tagger.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>File,12</string>
  <string>Path,0</string>
  <string>Size,1</string>
  <string>Attributes,2</string>
  <string>Created,3</string>
  <string>Track,4</string>
  <string>Artist,5</string>
  <string>Album,6</string>
  <string>Title,7</string>
  <string>Year,8</string>
  <string>Comment,9</string>
  <string>Genre,10</string>
  <string>Length,11</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection columns {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["columns"]));
            }
            set {
                this["columns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string last_dir {
            get {
                return ((string)(this["last_dir"]));
            }
            set {
                this["last_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool restore_dir {
            get {
                return ((bool)(this["restore_dir"]));
            }
            set {
                this["restore_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool scan_subdirs {
            get {
                return ((bool)(this["scan_subdirs"]));
            }
            set {
                this["scan_subdirs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool view_ver1 {
            get {
                return ((bool)(this["view_ver1"]));
            }
            set {
                this["view_ver1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>&lt;K&gt;-&lt;A&gt;-&lt;B&gt;-&lt;T&gt;</string>
  <string>&lt;A&gt;\&lt;B&gt;\&lt;K&gt;-&lt;T&gt;</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection org_formats {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["org_formats"]));
            }
            set {
                this["org_formats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool org_ver1 {
            get {
                return ((bool)(this["org_ver1"]));
            }
            set {
                this["org_ver1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool org_overwrite {
            get {
                return ((bool)(this["org_overwrite"]));
            }
            set {
                this["org_overwrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool org_copy {
            get {
                return ((bool)(this["org_copy"]));
            }
            set {
                this["org_copy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string org_root_dir {
            get {
                return ((string)(this["org_root_dir"]));
            }
            set {
                this["org_root_dir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>&lt;K&gt;-&lt;T&gt;</string>
  <string>&lt;A&gt; - &lt;B&gt; - &lt;T&gt;</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection tagv12file_formats {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["tagv12file_formats"]));
            }
            set {
                this["tagv12file_formats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>&lt;K&gt;-&lt;T&gt;</string>
  <string>&lt;A&gt; - &lt;B&gt; - &lt;T&gt;</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection tagv22file_formats {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["tagv22file_formats"]));
            }
            set {
                this["tagv22file_formats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>&lt;K&gt;-&lt;T&gt;</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection file2tagv1_formats {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["file2tagv1_formats"]));
            }
            set {
                this["file2tagv1_formats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>&lt;K&gt;-&lt;T&gt;</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection file2tagv2_formats {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["file2tagv2_formats"]));
            }
            set {
                this["file2tagv2_formats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>File,1</string>
  <string>Path,1</string>
  <string>Size,1</string>
  <string>Attributes,1</string>
  <string>Created,1</string>
  <string>Accessed,1</string>
  <string>Modified,1</string>
  <string>Album,1</string>
  <string>Artist,1</string>
  <string>Title,1</string>
  <string>Track,1</string>
  <string>TrackCount,1</string>
  <string>Disc,1</string>
  <string>DiscCount,1</string>
  <string>Comment,1</string>
  <string>Year,1</string>
  <string>Genre,1</string>
  <string>Length,1</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection cols {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["cols"]));
            }
            set {
                this["cols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<K>-<A>-<B>-<T>")]
        public string org_last_format {
            get {
                return ((string)(this["org_last_format"]));
            }
            set {
                this["org_last_format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Current")]
        public string pref_default_type {
            get {
                return ((string)(this["pref_default_type"]));
            }
            set {
                this["pref_default_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<K>-<T>")]
        public string file2tagv1_last_format {
            get {
                return ((string)(this["file2tagv1_last_format"]));
            }
            set {
                this["file2tagv1_last_format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<K>-<T>")]
        public string file2tagv2_last_format {
            get {
                return ((string)(this["file2tagv2_last_format"]));
            }
            set {
                this["file2tagv2_last_format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<K>-<T>")]
        public string tagv12file_last_format {
            get {
                return ((string)(this["tagv12file_last_format"]));
            }
            set {
                this["tagv12file_last_format"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<K>-<T>")]
        public string tagv22file_last_format {
            get {
                return ((string)(this["tagv22file_last_format"]));
            }
            set {
                this["tagv22file_last_format"] = value;
            }
        }
    }
}
